version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w7c1c9a7
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nginx_image_v2 .
      - docker tag nginx_image_v2:latest public.ecr.aws/w7c1c9a7/ecr_doc_img_2:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/w7c1c9a7/ecr_doc_img_2:latest
